org.gradle.jvmargs=-Xmx1G -XX:+UseG1GC -Dfile.encoding=UTF-8
javaVersion=21

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1

mod_version=1.0-SNAPSHOT
maven_group=com.foxsoftware
archives_base_name=SFE

spring_boot_version=3.3.3
lombok_version=1.18.32
jackson_version=2.17.1
flyway_version=10.16.0
sqlite_driver_version=3.46.0.0
micrometer_version=1.12.5
bucket4j_version=8.15.0
jjwt_version=0.11.5

junit_version=5.10.2
mockito_version=5.11.0